### ISSUE TITLE
HtmlUnit does not load entire page

### ISSUE THREAD

**Issue by jgmcode** [HtmlUnit/htmlunit#114]
I have checked that HtmlUnit does not load part of this page:

    https://www.milanuncios.com/mis-anuncios/

When inspected with a browser, the section:

    <div class="ma-LayoutBasicMainContent">

Has into a lot of contents. But when loaded by HtmlUnit... it is empty!

I have tried various webClient switches, including

    webClient.setAjaxController(new NicelyResynchronizingAjaxController());
    webClient.getOptions().setDownloadImages(true);
    webClient.getOptions().setCssEnabled(true);
    webClient.getOptions().setJavaScriptEnabled(true);
    webClient.setJavaScriptTimeout(10000);

But always with same result: The "ma-LayoutBasicMainContent" section is not loaded. This is the code I use:

    import com.gargoylesoftware.htmlunit.NicelyResynchronizingAjaxController;
    import com.gargoylesoftware.htmlunit.WebClient;
    import com.gargoylesoftware.htmlunit.html.*;

    class MarnvHtmlUnitTest {

    public static void main(String[] args) {

        WebClient webClient = null;

        try {

            final long javascriptTimeout = 10000;

            webClient = new WebClient();
            webClient.setAjaxController(new NicelyResynchronizingAjaxController());
            webClient.getOptions().setDownloadImages(true);
            webClient.getOptions().setCssEnabled(true);
            webClient.getOptions().setJavaScriptEnabled(true);
            webClient.setJavaScriptTimeout(10000);

            String loginURL = "https://www.milanuncios.com/mis-anuncios/";
            System.out.println("Connecting to " + loginURL + " (" + webClient.getBrowserVersion() + ")");

            HtmlPage page = webClient.getPage(loginURL);
            System.out.print("    Waiting for Javascript to complete...");
            long millis = System.currentTimeMillis();
            webClient.waitForBackgroundJavaScript(javascriptTimeout);                              
            System.out.println(System.currentTimeMillis() - millis + " milliseconds");
            if (!page.asText().contains("gestiona tus anuncios")) {
                System.out.println("ERROR!");
                System.out.println(page.asXml());
                System.out.println("EXITING. " + webClient.getWebWindows().size());
                return;
            }

            System.out.println("OK");

        } catch (Exception e) {
            e.printStackTrace();
        }
        finally {
            if (webClient != null)
                webClient.close();
        }
    }
    }

In case of correct page loading, the page should contain the text "gestiona tus anuncios".
Note that the call to "waitForBackgroundJavaScript" returns inmediately, which for me it's strange... it normaly waits some seconds until the page is completely loaded.

I am using HtmlUnit 2.36.0.

Thank you in advance for your help.

**Comment by rbri** [comment]
We have several reports like this, will try to figure out what is going wrong here.

**Comment by jgmcode** [comment]
Hi
Yes.. I think it could be related with some Javascript errors during page loading:

ene 02, 2020 11:25:35 PM com.gargoylesoftware.htmlunit.javascript.DefaultJavaScriptErrorListener scriptException
GRAVE: Error during JavaScript execution
======= EXCEPTION START ========
Exception class=[java.lang.RuntimeException]
com.gargoylesoftware.htmlunit.ScriptException: Exception invoking all
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:883)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:617)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:534)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:336)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:763)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:739)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:103)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1002)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:362)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:236)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:257)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:792)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:748)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1175)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1115)
	at net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:219)
	at net.sourceforge.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:303)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3146)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2074)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:922)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:438)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:389)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:991)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:246)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:190)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:269)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:160)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:534)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:400)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:317)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:469)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:450)
	at MarnvHtmlUnitTest.main(MarnvHtmlUnitTest.java:30)
Caused by: java.lang.RuntimeException: Exception invoking all
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:214)
	at net.sourceforge.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:391)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1675)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1010)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:424)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:322)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3628)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:123)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$2.doRun(JavaScriptEngine.java:754)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:868)
	... 34 more
Caused by: java.lang.NullPointerException
	at com.gargoylesoftware.htmlunit.javascript.host.Promise.settleAll(Promise.java:264)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise.all(Promise.java:342)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise.all(Promise.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:188)
	... 44 more

**Comment by jgmcode** [comment]
Maybe the clue is on the line 338 of Promise.java
Seems that args[0] is not an instance of NativeArray

**Comment by rbri** [comment]
Ok, i think i have fixed this (the js error). Please check twitter (https://twitter.com/HtmlUnit) for info about a new snapshot build.

**Comment by jgmcode** [comment]
Hi!
ok, with the snapshot, the NullPointer disappeared and more sections of the page are loaded.
But... the interesting section are still not loaded... these are the exception I can found:

GRAVE: Error during JavaScript execution
======= EXCEPTION START ========
Exception class=[net.sourceforge.htmlunit.corejs.javascript.JavaScriptException]
com.gargoylesoftware.htmlunit.ScriptException: Error: Minified React error #327; visit https://reactjs.org/docs/error-decoder.html?invariant=327 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/d0b3667e.js#2)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:883)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:336)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:812)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:784)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2567)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2560)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:171)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.dispatchEvent(EventTarget.java:271)
	at com.gargoylesoftware.htmlunit.javascript.host.MessagePort$1.lambda$execute$0(MessagePort.java:109)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.host.MessagePort$1.execute(MessagePort.java:109)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:934)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.processPostponedActions(JavaScriptEngine.java:1003)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise.<init>(Promise.java:138)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.newInstance(MemberBox.java:236)
	at net.sourceforge.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:460)
	at com.gargoylesoftware.htmlunit.javascript.RecursiveFunctionObject.call(RecursiveFunctionObject.java:191)
	at net.sourceforge.htmlunit.corejs.javascript.BaseFunction.construct(BaseFunction.java:366)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1718)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise.<init>(Promise.java:132)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.newInstance(MemberBox.java:236)
	at net.sourceforge.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:460)
	at com.gargoylesoftware.htmlunit.javascript.RecursiveFunctionObject.call(RecursiveFunctionObject.java:191)
	at net.sourceforge.htmlunit.corejs.javascript.BaseFunction.construct(BaseFunction.java:366)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1718)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at net.sourceforge.htmlunit.corejs.javascript.BoundFunction.call(BoundFunction.java:53)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1674)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:322)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3607)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise$3$1.run(Promise.java:409)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise$3.run(Promise.java:444)
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:424)
	at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: net.sourceforge.htmlunit.corejs.javascript.JavaScriptException: Error: Minified React error #327; visit https://reactjs.org/docs/error-decoder.html?invariant=327 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/d0b3667e.js#2)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1215)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:803)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:868)
	... 55 more
JavaScriptException value = Error: Minified React error #327; visit https://reactjs.org/docs/error-decoder.html?invariant=327 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
== CALLING JAVASCRIPT ==
  function () {
      if (null !== b) {
          var e = t.unstable_now();
          T = e + w;
          try {
              b(!0, e) ? x.postMessage(null) : (g = !1, b = null);
          }
          catch (n) {
              throw x.postMessage(null), n;
          }
      } else {
          g = !1;
      }
  }
======= EXCEPTION END ========

ene 04, 2020 8:40:09 PM com.gargoylesoftware.htmlunit.WebConsole info
INFORMACIÓN: Hydratate took 318.0310999993235 milliseconds.
ene 04, 2020 8:40:09 PM com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl runSingleJob
GRAVE: Job run failed with unexpected RuntimeException: TypeError: Cannot call method "call" of undefined (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/5f67b524.js#1)
net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot call method "call" of undefined (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/5f67b524.js#1)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4298)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4276)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4309)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4328)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:4345)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2585)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2578)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1519)
	at script.c(https://scm-milanuncios-frontend-pro.milanuncios.com/spa/5f67b524.js:1)
	at script(https://scm-milanuncios-frontend-pro.milanuncios.com/spa/fd19632f.js:1)
	at script.c(https://scm-milanuncios-frontend-pro.milanuncios.com/spa/5f67b524.js:1)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at net.sourceforge.htmlunit.corejs.javascript.BoundFunction.call(BoundFunction.java:53)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:322)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3607)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise$3$1.run(Promise.java:409)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise$3.run(Promise.java:444)
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:424)
	at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148)
	at java.lang.Thread.run(Unknown Source)

ene 04, 2020 8:40:09 PM com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl runSingleJob
GRAVE: Job run failed with unexpected RuntimeException: TypeError: Cannot call method "logoutUserUseCase" of undefined (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/0d8f662f.js#2)
net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot call method "logoutUserUseCase" of undefined (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/0d8f662f.js#2)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4298)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4276)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4309)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4328)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:4345)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2585)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2578)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getElemFunctionAndThis(ScriptRuntime.java:2524)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1530)
	at script(https://scm-milanuncios-frontend-pro.milanuncios.com/spa/0d8f662f.js:2)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:322)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3607)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise$3$1.run(Promise.java:409)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.host.Promise$3.run(Promise.java:444)
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:424)
	at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148)
	at java.lang.Thread.run(Unknown Source)

ene 04, 2020 8:40:09 PM com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine init
ADVERTENCIA: Error during JavaScriptEngine.init(WebWindow, Context)
TypeError: Cannot modify readonly property: constructor. (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/0d8f662f.js#2)
prototype: HTMLOptionElement
ene 04, 2020 8:40:09 PM com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine init
ADVERTENCIA: Error during JavaScriptEngine.init(WebWindow, Context)
TypeError: Cannot modify readonly property: constructor. (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/0d8f662f.js#2)
prototype: MutationObserver
ene 04, 2020 8:40:09 PM com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine init
ADVERTENCIA: Error during JavaScriptEngine.init(WebWindow, Context)
TypeError: Cannot modify readonly property: constructor. (https://scm-milanuncios-frontend-pro.milanuncios.com/spa/0d8f662f.js#2)
prototype: URL
863 milliseconds

**Comment by rbri** [comment]
see #755
